# Generated by Django 5.2.6 on 2026-03-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='screenshots',
            field=models.ManyToManyField(blank=True, related_name='games', to='games.screenshot', verbose_name='Скриншоты'),
        ),
    ]
