# Generated by Django 5.2.6 on 2026-04-04 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_screenshots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='screenshots',
        ),
    ]
